name: oh_auth_2
description: A flutter library for the industry-standard protocol for authorization.
version: 1.0.1+1
authors:
  - Murtaza Akbari <murtazasakbari@gmail.com>
homepage: https://github.com/Murtaza0xFF/OhAuth2
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_webview_plugin: ^0.3.0+2
  json_annotation: ^2.0.0
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^2.0.0
  build_runner: ^1.0.0


